.TH DWM 1 dwm\-VERSION
.SH NAME
phyOS\-dwm \- dynamic window manager
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
phyOS-dwm is a fork of dwm for phyOS
.P
dwm "orders" windows based on recency and primacy, while dwm layouts may
change, the most recent "master" window is shown in the most prominent
position. There are bindings for cycling through and promoting windows to the
master position.
.P
Windows are grouped by tags. Each window can be tagged with one or multiple
tags. Selecting certain tags displays all windows with these tags.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.SH USAGE
.SS Status bar
.TP
.B pOS-make-bar
Run this script to make your own statusbar.
.TP
.B There are some actions when bar blocks are clicked.
 Action keys are, Left Click, Right Click, Middle Click.
.SS KEYBINDINGS
.TP
.B Caps Lock is equal to Win button. Also works as escape in terminal (vim).
.TP
.B Alt + Left Click
Hide clicked window
.TP
.B Alt + Tab
Navigate through all windows and focus selected (also maximize window)
.TP
.B Win + Tab
Navigate through current tag and focus selected (also maximize window)
.TP
.B Win + [0 .. 9]
Go to tag (0 and 9 inclusive, 0 shows all tags)
.TP
.B Win + Shift + [0 .. 9]
Send focused window to chosen tag
.TP
.B Win + [h, l]
Increase - decrease window size
.TP
.B Win + Shift + [h, l]
Go to previous tag - go to next tag
.TP
.B Win + [j, k]
Focus previous - focus next
.TP
.B Win + Shift + [j, k]
Move focused previous - move focused next
.TP
.B Alt + [h, l]
Send focused to previous monitor - send focused to next monitor
.TP
.B Alt + [j, k]
Focus previous monitor - focus next monitor
.TP
.B Win + s
Toggle sticky (show window on all tags)
.TP
.B Win + f
Toggle fullscreen
.TP
.B Win + q
Quit focused window
.TP
.B Win + Return
Spawn $TERMINAL
.TP
.B Win + [Esc, BackSpace]
Shutdown menu
.TP
.B Win + Shift + Return
Toggle scratchpad
.TP
.B Win + w
Spawn $BROWSER
.TP
.B Win + r
Spawn lf (file manager)
.TP
.B Win + a
Spawn applications menu
.TP
.B Win + b
Toggle - hide statusbar (current tag)
.TP
.B Win + Shift + b
Toggle - hide statusbar (all tags)
.TP
.B Win + d
Jump to bookmarked directory
.TP
.B Win + Shift + a
Spawn dmenu (execute any runnable)
.TP
.B Win + p
Spawn password manager (pass)
.TP
.B Alt + p
Stress monitor (s-tui)
.TP
.B Win + F4
Spawn sound options (pavucontrol)
.TP
.B Win + F5
Open display select (set resolution, refresh rate)
.TP
.B Win + F9
Mount drive
.TP
.B Win + F10
Unmount drive
.TP
.B Win + F11
Open camera
.TP
.B Printscreen
Screenshow full screen
.TP
.B Shift + Printscreen - Win + Shift + s
Screenshot (selected area, choose a window, full screen)
.TP
.B Win + `
Choose emoji and copy
.TP
.B Win + g
Toggle gaps
.TP
.B Win + x
Increase gaps
.TP
.B Win + Shift + x
Decrease gaps
.TP
.B Win + Shift + g
Toggle default gaps
.TP
.B Win + m
Increase master window count by 1
.TP
.B Win + Shift + m
Decrease master window count by 1
.TP
.B Win + Space
Set focused as master
.TP
.B Win + Shift + Space
Toggle floating
.TP
.B Alt + 1
Tiling layout mode
.TP
.B Alt + 2
Backstack layout mode
.TP
.B Alt + 3
Monocle layout mode (windows on top of another)
.TP
.B Alt + 4
Deck layout mode
.TP
.B Alt + 5
Spiral (fibonacci) layout mode
.TP
.B Alt + 6
Dwindle layout mode
.TP
.B Alt + 7
Centered master layout mode
.TP
.B Alt + 8
Centered floating master layout mode
.TP
.B Alt + 9
Floating layout mode
.SH SIGNALS
.TP
.B SIGHUP - 1
Restart the dwm process.
.TP
.B SIGTERM - 15
Cleanly terminate the dwm process.
.SH SEE ALSO
.BR dmenu (1),
.BR st (1)
.SH ISSUES
Java applications which use the XToolkit/XAWT backend may draw grey windows
only. The XToolkit/XAWT backend breaks ICCCM-compliance in recent JDK 1.5 and early
JDK 1.6 versions, because it assumes a reparenting window manager. Possible workarounds
are using JDK 1.4 (which doesn't contain the XToolkit/XAWT backend) or setting the
environment variable
.BR AWT_TOOLKIT=MToolkit
(to use the older Motif backend instead) or running
.B xprop -root -f _NET_WM_NAME 32a -set _NET_WM_NAME LG3D
or
.B wmname LG3D
(to pretend that a non-reparenting window manager is running that the
XToolkit/XAWT backend can recognize) or when using OpenJDK setting the environment variable
.BR _JAVA_AWT_WM_NONREPARENTING=1 .
.SH BUGS
Reach out to maintainer Arda Atci <arda@ftlabs.tech>
