static char bar_bg[]       = "#1e222a";
static char bar_fg[]       = "#96CDFB";
static char window_border_unfocused[]       = "#282737"; // unfocused window border
static char window_border_focused[]        = "#96CDFB";  // focused window border
static char seperator_fg[]       = "#c9cbff";
static char bar_optimal_fg[]       = "#ABE9B3";
static char bar_critical_fg[]         = "#F28FAD";
static char bar_status_text_fg[]       = "#eff1f5";
static char bar_lt_symbol_fg[]       = "#ABE9B3";
