#!/bin/bash

if [[ $1 = "add" ]]; then
	dir="$(pwd)/$2"
	ln -s "$dir" "$ZSHCFG/bookmarks/$3" && echo "Bookmark: $3 saved succesfully"
elif [[ $1 = "rm" ]]; then
	rm "$ZSHCFG/bookmarks/$2"
	echo "Bookmark: $2 erased succesfully"
else
	echo "Wrong operation, please use one of below:"
	echo "bm add 'source' 'aliasname' adds bookmark"
	echo "bm rm 'aliasname' deletes bookmark"
fi
